### ISSUE TITLE
System startup problems

### ISSUE THREAD

**Issue by wangjie0323** [pslade2/AugmentedCane#1]
![raspi](https://user-images.githubusercontent.com/52735784/143732383-4849a401-8698-48b2-a1f2-975d86f5b2d3.jpg)

What is the reason why I can't enter the system using the image you provided?

**Comment by pslade2** [comment]
Hi, this happens when a newer raspberry pi board is made, it has slightly different software. You can either use a fresh install of the raspberry pi operating system and download the code repository from here (you'll have to install dependencies). Or you can change a few files in the system image I provided for you board (instructions on how to do that here: https://raspberrypi.stackexchange.com/questions/127325/raspberry-pi-not-booting-recover4-elf-is-not-compatible).

**Comment by kenpower** [comment]
I had the same problem, but copying the start4*.elf files (as suggested in the SE answer) from a newer image did not help.

How do I find out what dependencies we need?

**Comment by pslade2** [comment]
Hi Ken. Did you make sure to copy the start4.elf files for you specific raspberry pi version? I've had success updating it for several different models of pi.

Otherwise I would suggest getting the latest Raspbian Image (I used a 2019 raspbian image) and installing the python dependencies for whichever script you are trying to run. Let me know if you have more questions!
